version: "3.7"
services:
    api:
        build:
            context: api/
            dockerfile: Dockerfile
        image: anylatex-api:latest
        volumes:
            - ./config.json:/backend/config.json
    nginx:
        build:
            context: nginx/
            dockerfile: Dockerfile
        image: anylatex-nginx:latest
        ports:
            - "4000:80"
        depends_on:
            - api
    compiler:
        build:
            context: compiler/
            dockerfile: Dockerfile
        image: anylatex-compiler:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./config.json:/backend/config.json
            - compiler_volume:/compiler-tmp
    mongo:
        image: mongo:4.0
        volumes:
            - mongodb_volume:/data/db
volumes:
    compiler_volume:
    mongodb_volume:

